### PR TITLE
Chart dependencies

### PR DESCRIPTION
**Pull request by ghost**
Original PR on Trains chart was referred here:
https://github.com/allegroai/clearml-server-k8s/pull/12

### CODE REVIEW

**Comment by ghost** [comment]
also fixed a typo in ci checks

**Comment by sapir-allegro** [comment]
Hey @valeriano-manassero,
I see that the versions you used for Redis, MongoDB and Elasticsearch are not the same versions we use in ClearML.
Any specific reason? Can you change those to the versions we use in ClearML?

**Comment by ghost** [comment]
> Hey @valeriano-manassero,
> I see that the versions you used for Redis, MongoDB and Elasticsearch are not the same versions we use in ClearML.
> Any specific reason? Can you change those to the versions we use in ClearML?

I just tested latest stable on my testing cluster and they where working. I don't think there is any problem do downgrade to already used version. Will test the chart and update PR asap!

**Comment by ghost** [comment]
Hey @sapir-allegro , I updated dependencies versions to get in sync with the ones previously used.

Since I'm now using my fork to deploy ClearML I tested this PR very quickly and looks good to me but I suggest to install on one of your cluster to do some intensive tests.

Jfi even newest versions of mongo,redis and elastic works from what I can see.

Let me know if it's ok now.

**Comment by sapir-allegro** [comment]
Hey @valeriano-manassero,
Thanks! this looks great. 
I was also wondering about the env variables that were removed.
We've had some elastic properties defined using env variables and I see that you removed all of them.
Can you please add those back?

Regarding the newer versions - I'm happy to hear that it works! But we still need to test those before making such a change and it would probably take some time. I prefer using the current versions so we can merge this PR asap :)

**Comment by ghost** [comment]
Hey @sapir-allegro , I put back env vars as requested. Just too be extremely sure, since this is a big PR, I suggest to test a complete installation on your environments. As I said before, I tried this chart on my env and lgtm but better play safe 😄

**Comment by sapir-allegro** [comment]
Great thanks!
And no worries we will test it before merging.

**Comment by jkhenning** [comment]
@valeriano-manassero can we close this PR now that it was actually adopted as the `clearml-server-cloud-ready` chart? 🙂

**Comment by ghost** [comment]
Absolutely, just did it 👍

**Pull request closed without merging**
