### PR TITLE
Agent configurable queues

### PR DESCRIPTION
**Pull request by ghost**
With this implementation queues are configurable by the chart user on `queues` parameter that will be passed to agent command.

### CODE REVIEW

**Comment by jkhenning** [comment]
Thanks @valeriano-manassero, I'll take a look and merge soon 👍

**Comment by sapir-allegro** [comment]
Hey @valeriano-manassero,
Can you please commit to this pr the changes done [here](https://github.com/allegroai/trains-server-k8s/commit/156e78a029ac62bdbf80726d5eb4db33675d2029), and resolve the conflicts?

**Comment by sapir-allegro** [comment]
Hey @valeriano-manassero,
Following your latest pr that was merged ([here](https://github.com/allegroai/trains-server-k8s/commit/156e78a029ac62bdbf80726d5eb4db33675d2029)), can you please commit the changes and resolve the conflicts so we can also merge this one?

**Comment by ghost** [comment]
> Hey @valeriano-manassero,
> Following your latest pr that was merged ([here](https://github.com/allegroai/trains-server-k8s/commit/156e78a029ac62bdbf80726d5eb4db33675d2029)), can you please commit the changes and resolve the conflicts so we can also merge this one?

PR should be fixed now

**Pull request merged**
