### PR TITLE
Agent docker mode enable/disable

### PR DESCRIPTION
**Pull request by ghost**
With this it's possible to disable dockerMode for an Agent deployment in k8s. I found this especially useful when I don't want to get over K8s itself creating directly containers in Docker daemon.
Moreover, in this way it's possible to directly use the GPU attached to agent pod by a gpu-operator.

I didn't update version in Chart.yaml because I'm not sure if I need to raise a specific PR for that. If needed I can add it here.

### CODE REVIEW

**Comment by bmartinn** [comment]
Thanks @valeriano-manassero !
How do I switch between the different modes ?

**Comment by ghost** [comment]
> Thanks @valeriano-manassero !
> How do I switch between the different modes ?

In values.yaml there is now `agent.dockerMode` you can override. I set the default a `true` so the chart is totally backward compatible acting like before.

**Comment by bmartinn** [comment]
@valeriano-manassero , nice!
LGTM :)

**Comment by ghost** [comment]
@bmartinn do I have to bump up Chart version too?

**Comment by jkhenning** [comment]
Hi @valeriano-manassero,

> do I have to bump up Chart version too?

No need, we'll take care of that in the Helm repository once we release a version.

**Pull request merged**
