### PR TITLE
use == when a custom agentVersion is set

### PR DESCRIPTION
**Pull request by ghost**
When using the custom value
```
agent:
  agentVersion: "0.16.2rc0"
```
the agent will fail since the `pip install` will miss `==`

This PR fix this issue.

### CODE REVIEW

**Comment by bmartinn** [comment]
Thanks @valeriano-manassero !
Maybe we should test if the `agentVersion` doesn't start with `=` `<` `>` so that we could support something like `agentVersion: ">=0.16.2rc0"`
What do you think?

**Comment by ghost** [comment]
> Thanks @valeriano-manassero !
> 
> Maybe we should test if the `agentVersion` doesn't start with `=` `<` `>` so that we could support something like `agentVersion: ">=0.16.2rc0"`
> 
> What do you think?

I can improve the PR to include a configurable prefix.

**Comment by bmartinn** [comment]
That would be awesome! 🎊

**Comment by ghost** [comment]
I just added the `agentVersionComparisonOperator` variable that should be useful having more control over the agent installation

**Comment by bmartinn** [comment]
@valeriano-manassero Thanks!

**Comment by sapir-allegro** [comment]
Hey @valeriano-manassero!
There are two issues I wish to discuss:
1. I think that's a bit too complex, we should think of a way to make it more readable for new users.
Do you have an idea of how to do so?
2. We need to make sure we are backwards compatible, so adding `"=="` as default value could be problematic.
I was thinking that the default value should be empty and so it wouldn't create cases such as `python3 -m pip install trains-agent====0.16.3` for existing users, what do you think?

**Comment by ghost** [comment]
@sapir-allegro I understand your point. So I updated PR to include only a message for who is going to implement the custom agentVersion. It's not much but may avoid some headache during a custom clause.yaml creation. wdyt?

**Comment by sapir-allegro** [comment]
I agree, it seems like a good idea.

**Pull request merged**
