### PR TITLE
External chart dependencies

### PR DESCRIPTION
**Pull request by ghost**
I see usually a good practice is to use helm dependencies when possible to have a smoother maintenance duties.

This PR is still WIP so I started with Redis substituting the custom deployment with a new one using official Bitnami chart.
In this way it's easier to maintain and we still have full control on version/custom configs on Redis.

If you like this implementation I can do the same for Elasticsearch and MongoDB to this PR before requesting a review.

### CODE REVIEW

**Comment by jkhenning** [comment]
Hi @valeriano-manassero ,

I assume the removal of the persistent storage section is due to the fact that this will be handled by the specific Redis, MongoDB and Elastic charts?

**Comment by ghost** [comment]
> I assume the removal of the persistent storage section is due to the fact that this will be handled by the specific Redis, MongoDB and Elastic charts?

Exactly. Atm I just implemented Redis but you can see the section `redis:` in `values.yaml` that is totally configurable with these values https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml 

So you can configure also persistent storage or clustering configurations of persist itself without impacting Trains config.

I can try to do same for Elastic and MongoDB so you will have to maintain only Trains chart using these apps as dependency

**Comment by jkhenning** [comment]
> I can try to do same for Elastic and MongoDB so you will have to maintain only Trains chart using these apps as dependency

That would be great! Thanks 😄

**Comment by ghost** [comment]
MongoDB added to the refactoring process. Still WIP since Elasticsearch needs to be moved too.

**Comment by ghost** [comment]
Finally WIP is over.

I squashed some commits to get a clear history.
Redis, MongoDB and Elasticsearch are now managed as external dependencies maintaining full control using `values`.

Let me know if it works for you.

**Comment by ghost** [comment]
Closing so I will propose changes on ClearML chart.

**Pull request closed without merging**
